Problem statement.

Build a recommender system by using cosine simillarties score.

In [1]:
import pandas as pd
import numpy as np

In [3]:
book=pd.read_csv('book.csv',encoding='latin-1')
book

,Unnamed: 0,User.ID,Book.Title,Book.Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6
...,...,...,...,...
9995,9996,162121,American Fried: Adventures of a Happy Eater.,7
9996,9997,162121,Cannibal In Manhattan,9
9997,9998,162121,How to Flirt: A Practical Guide,7
9998,9999,162121,Twilight,8
9999,10000,162129,Kids Say the Darndest Things,6

In [21]:
book_1=book.drop('Unnamed: 0',axis=1)
book_1

      User.ID                                         Book.Title  Book.Rating
2401        8                                              Wings            5
2400        8  The Western way: A practical guide to the West...            5
2399        8                            Ancient Celtic Romances            5
2402        8                                           Truckers            5
2405        8                                  The Art Of Celtia            7
...       ...                                                ...          ...
2395   278854      La crÃƒÂ³nica del PerÃƒÂº (CrÃƒÂ³nicas de AmÃƒÂ©rica)            7
2398   278854  Celtic Mythology (Library of the World's Myths...            8
2393   278854                         A corrente de Trewis Scott            7
2394   278854                                      As valkÃƒÂ­rias            7
2397   278854     A Treasury of Irish Myth, Legend, and Folklore            6

[10000 rows x 3 columns]

In [22]:
len(book_1['Book.Title'].unique())

9659

In [26]:
books_df =book_1.pivot_table(index='User.ID',
                                 columns='Book.Title',
                                 values='Book.Rating').reset_index()
books_df

Book.Title,User.ID,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,Ãƒ?Ã‚?bermorgen.
0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2177,278846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2178,278849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2179,278851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN
2180,278852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2181,278854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
books_df.index = book_1['User.ID'].unique()

In [30]:
books_df

Book.Title,User.ID,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,Ãƒ?Ã‚?bermorgen.
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,278846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278849,278849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278851,278851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN
278852,278852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278854,278854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
books_df.fillna(0, inplace=True)

In [32]:
books_df

Book.Title,User.ID,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,Ãƒ?Ã‚?bermorgen.
8,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
#from scipy.spatial.distance import cosine, correlation

In [34]:
user_sim = 1 - pairwise_distances( books_df.values,metric='cosine')

In [35]:
user_sim

array([[1.        , 0.39429125, 0.40634798, ..., 0.4738791 , 0.4738791 ,
        0.4738791 ],
       [0.39429125, 1.        , 0.71347724, ..., 0.83205029, 0.83205029,
        0.83205029],
       [0.40634798, 0.71347724, 1.        , ..., 0.85749292, 0.85749293,
        0.85749292],
       ...,
       [0.4738791 , 0.83205029, 0.85749292, ..., 1.        , 1.        ,
        0.99999999],
       [0.4738791 , 0.83205029, 0.85749293, ..., 1.        , 1.        ,
        1.        ],
       [0.4738791 , 0.83205029, 0.85749292, ..., 0.99999999, 1.        ,
        1.        ]])

In [36]:
user_sim_df = pd.DataFrame(user_sim)

In [39]:
user_sim_df.index = books_df['User.ID'].unique()
user_sim_df.columns = books_df['User.ID'].unique()

In [40]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

          8         9         10        12        14
8   0.000000  0.394291  0.406348  0.364044  0.395067
9   0.394291  0.000000  0.713477  0.639199  0.693670
10  0.406348  0.713477  0.000000  0.658744  0.714881
12  0.364044  0.639199  0.658744  0.000000  0.640457
14  0.395067  0.693670  0.714881  0.640457  0.000000

In [41]:
user_sim_df.idxmax(axis=1)[8:14]

22    278755
26    278755
32    278755
39    278755
42    278755
44    278755
dtype: int64

In [47]:
book[(book['User.ID']==8) | (book['User.ID']==278755)]

,Unnamed: 0,User.ID,Book.Title,Book.Rating
2401,2402,8,Wings,5
2400,2401,8,The Western way: A practical guide to the West...,5
2399,2400,8,Ancient Celtic Romances,5
2402,2403,8,Truckers,5
2405,2406,8,The Art Of Celtia,7
2403,2404,8,Keepers of the Earth Teachers Guide,6
2404,2405,8,The Celts Activity Book,6
2320,2321,278755,"The Elements of Style, Fourth Edition",1

In [55]:
reader1=book[(book['User.ID']==8)]
reader1

,Unnamed: 0,User.ID,Book.Title,Book.Rating
2401,2402,8,Wings,5
2400,2401,8,The Western way: A practical guide to the West...,5
2399,2400,8,Ancient Celtic Romances,5
2402,2403,8,Truckers,5
2405,2406,8,The Art Of Celtia,7
2403,2404,8,Keepers of the Earth Teachers Guide,6
2404,2405,8,The Celts Activity Book,6

In [54]:
reader2=book[(book['User.ID']==278755)]
reader2

      Unnamed: 0  User.ID                             Book.Title  Book.Rating
2320        2321   278755  The Elements of Style, Fourth Edition            1

In [58]:
pd.merge(reader1,reader2,on='Book.Title',how='outer')

,Unnamed: 0_x,User.ID_x,Book.Title,Book.Rating_x,Unnamed: 0_y,User.ID_y,Book.Rating_y
0,2402.0,8.0,Wings,5.0,NaN,NaN,NaN
1,2401.0,8.0,The Western way: A practical guide to the West...,5.0,NaN,NaN,NaN
2,2400.0,8.0,Ancient Celtic Romances,5.0,NaN,NaN,NaN
3,2403.0,8.0,Truckers,5.0,NaN,NaN,NaN
4,2406.0,8.0,The Art Of Celtia,7.0,NaN,NaN,NaN
5,2404.0,8.0,Keepers of the Earth Teachers Guide,6.0,NaN,NaN,NaN
6,2405.0,8.0,The Celts Activity Book,6.0,NaN,NaN,NaN
7,NaN,NaN,"The Elements of Style, Fourth Edition",NaN,2321.0,278755.0,1.0